### ISSUE TITLE
Замечания 

### ISSUE THREAD

**Issue by JohnKhandygo** [Dimitriy-Gulyaev/JavaTask1#1]
- [x] Добавить правильно сконфигурированный .gitignore file. В .gitignore файле описываются файлы и директории, которые необходимо исключить при работе с данным репоиторием в git. В число таких файлов, как правило, включают специфичные для пользователей файлы, что позволяет избежать конфликтов при конкурентной работе с репозиторием. В частности, сюда целесообразно отнести файлы, [генерируемые IDE](https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems), поскольку их формат и содержание может отличаться от версии к версии. Для генерации .gitignore в idea удобно использовать [.ignore плагин](https://plugins.jetbrains.com/plugin/7495--ignore).
- [x] `Train::addStation` позволяет добавить несколько одинаковых станций. 
- [x] Реализация `hashCode` для `Train` не соответствует реализации `equals`.
- [x]  `TrainSchedule::addTrain` допускает время типа `24:X`.
- [x] В `TrainSchedule::deleteTrain` каждый раз пересчитываете время.
- [x] В `TrainSchedule::deleteTrain` несколько раз берете один и тот же элемент из `trains`. В случае использования `ArrayList` это не критично по производительности, однако раздувает код.
- [x] Используя функции `Train::deleteStation` и `TrainSchedule::deleteTrain`, нельзя программно определить, была ли действительно совершена операция или такой станции/поезда просто не существует. Иногда такое бывает полезно. Как правило, используется два варианта: добавить `boolean` результат или возвращать удаленное значение (null, если такого значения не было). 
- [x] Функция `TrainSchedule::findTrain` может вернуть `null`, что может быть не очень удобно для пользователя Вашей библиотеки. Лучше использовать `Optional`.
- [x] Имена классов в java, включая тестовые классы, принято называть в UpperCamelCase.
- [x] Тестовые методы, как правило, не описывают в javadoc. В основном потому, что javadoc нужен для сторонних пользователей, в то время как тесты, как правило, не зашиваются в jar'ник, то есть являются строго внутренним артефактом. Вместо этого тестовым методам стараются давать как можно более говорящие названия, вплоть до `whenIDoSomething_SomethingHappens`.
- [x] Конструктор класса `Train` допускает некорректные названия поездов и станций (например, пустая строка).
- [x] Вообще у Вас методы не проверяют возможность работы с `null`. В некоторых местах это может сломать логику всего приложения.
- [x] Нет теста, который бы проверял, что кидается исключение в случае добавления существующего поезда. 
- [x] Вообще при формировании тестов принято пользоваться концепцией [given - when - than](https://martinfowler.com/bliki/GivenWhenThen.html). То есть, например, Ваш метод `testAddTrain` стоит разбить на три разных метода, каждый из которых проверяет свой сценарий. То же самое касается и других тестов.

**Comment by JohnKhandygo** [comment]
- [ ] Для сравнения объектов (в том числе String) нельзя использовать оператор `==`, лучше использовать `equals`. Подробнее смотри [здесь](https://stackoverflow.com/questions/7520432/what-is-the-difference-between-vs-equals-in-java). В случае `str == ""` лучше вовсе использовать `str.isEmpty()`
- [ ] У Вас по коду часто встречается проверка `if (someString == null || someString == "") throw new IllegalArgumentException("Invalid somewhat name");`. Повторяющийся код стоит вынести в отдельную функцию. 
- [ ] Метод `deleteStation` можно сократить до двух строк. Смотри javadoc метода `List::remove(Object)` [здесь](https://docs.oracle.com/javase/8/docs/api/java/util/List.html#remove-java.lang.Object-) или ctrl + Q в идее, когда курсор стоит на методе.
- [ ] `findTrain` не возвращает `Optional`. Идея была именно в том, чтобы Вы вернули экземпляр `Optional<Train>`, а пользователь уже сам решит, кидать ему исключение или нет.
- [ ] Классы `Train` и `TrainSchedule` достаточно объемные, когда они объявлены в одном файле легко запутаться. Разнесите их по разным классам.
- [ ] То же самое касается и тестов. Тестовые методы лучше разбить по классам в зависимости от того, функциональность какого класса они проверяют.

**Comment by Dimitriy-Gulyaev** [comment]
Проект переехал в репозиторий NewJavaTask1, т.к. он совершенно поломался, и удобнее было создать заново. Всё исправил. Извините за неудобства.
