### ISSUE TITLE
Task 2.0

### ISSUE THREAD

**Issue by JohnKhandygo** [Dimitriy-Gulyaev/JavaTask1#2]
**Общая формулировка**
Разработать консольную утилиту, реализующую указанную в задании функциональность, на языках Java и/или Kotlin. При проектировании использовать объектно-ориентированный подход. Разработать автоматические тесты для отдельных частей программы. Написанный код держать в отдельном проекте или модуле в репозитории на GitHub.

**tail**
Выделение из текстового файла его конца некоторого размера:
fileN задаёт имя входного файла. Если параметр отсутствует, следует считывать входные данные с консольного ввода. Если параметров несколько, то перед выводом для каждого файла следует вывести его имя в отдельной строке.
Флаг -o ofile задаёт имя выходного файла (в данном случае ofile). Если параметр отсутствует, следует выводить результат на консольный вывод.
Флаг -с num, где num это целое число, говорит о том, что из файла нужно извлечь последние num символов.
Флаг -n num, где num это целое число, говорит о том, что из файла нужно извлечь последние num строк.

Command line: tail [-c num|-n num] [-o ofile] file0 file1 file2 …

В случае, когда какое-нибудь из имён файлов неверно или указаны одновременно флаги -c и -n, следует выдать ошибку. Если ни один из этих флагов не указан, следует вывести последние 10 строк.

Кроме самой программы, следует написать автоматические тесты к ней.

В readme также необходимо добавить инструкцию по сборке и запуску Вашего консольного приложения. Лучше всего, чтобы сборка/запуск были офрмлены в виде скриптов.

**Comment by Dimitriy-Gulyaev** [comment]
Ссылка на репозиторий проекта: https://github.com/Dimitriy-Gulyaev/JavaTask2

**Comment by JohnKhandygo** [comment]
Перенес условие задание в новый репозиторий. Все замечания будут появляться там.
